default:
  image: ghcr.io/siemens/kas/kas-isar:4.3.2

variables:
  GIT_STRATEGY: clone

.common-build: &common-build
  stage: build
  before_script:
    - export http_proxy=$HTTP_PROXY
    - export https_proxy=$HTTPS_PROXY
    - export ftp_proxy=$FTP_PROXY
    - export no_proxy=$NO_PROXY
    - export DISTRO_APT_PREMIRRORS=$DISTRO_APT_PREMIRRORS
  artifacts:
    name: "logs-$CI_JOB_ID"
    paths:
      - build/tmp/work/*/*/*/temp
      - build/job-results
    reports:
      junit:
        - build/job-results/job*/results.xml
    when: always
    expire_in: 1 week


.docker-isar: &docker-isar
  image: ghcr.io/ilbers/docker-isar:3.2.3


.use-default-image:
  rules:
    - &use-default-image
      if: $IMAGE
      when: never

.use-docker-isar-image:
  rules:
    - &use-docker-isar-image
      if: $IMAGE != 'docker-isar'
      when: never


dev-ci:
  <<: *common-build
  rules:
    - *use-default-image
    - if: $TESTSUITE == 'dev' || $CI_PIPELINE_SOURCE != 'schedule'
  script:
    - scripts/ci_build.sh -T dev

fast-ci:
  <<: *common-build
  rules:
    - *use-default-image
    - if: $TESTSUITE == 'fast'
  script:
    - scripts/ci_build.sh -T fast

full-ci:
  <<: *common-build
  rules:
    - *use-default-image
    - if: $TESTSUITE == null && $CI_PIPELINE_SOURCE == 'schedule'
    - if: $TESTSUITE == 'full'
  script:
    - PREVIOUS_SHA="$(cat .CI_COMMIT_SHA || true)"
    - if [ "$CI_COMMIT_SHA" != "$PREVIOUS_SHA" ]; then
          echo "$CI_COMMIT_SHA" > .CI_COMMIT_SHA;
          scripts/ci_build.sh -T full;
      fi
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .CI_COMMIT_SHA


dev-ci-isar:
  <<: *docker-isar
  <<: *common-build
  rules:
    - *use-docker-isar-image
    - if: $TESTSUITE == 'dev'
  script:
    - scripts/ci_build.sh -T dev

fast-ci-isar:
  <<: *docker-isar
  <<: *common-build
  rules:
    - *use-docker-isar-image
    - if: $TESTSUITE == 'fast'
  script:
    - scripts/ci_build.sh -T fast

full-ci-isar:
  <<: *docker-isar
  <<: *common-build
  rules:
    - *use-docker-isar-image
    - if: $TESTSUITE == 'full'
  script:
    - scripts/ci_build.sh -T full
